# Generated by Django 5.2.8 on 2025-11-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directeur_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonddisponibe',
            name='date_ajout',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fonddisponibe',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
