# Generated by Django 5.2.8 on 2025-11-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportdepense',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
