# Generated by Django 5.2.8 on 2025-11-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_rapportdepense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportdepense',
            name='chantier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
