# Generated by Django 5.2.8 on 2025-11-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0003_rapportdepense_chantier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportdepense',
            name='fournisseur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
