# Generated by Django 5.2.8 on 2025-11-16 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeDecaissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chantier', models.CharField(blank=True, max_length=200, null=True)),
                ('motif', models.TextField()),
                ('status', models.CharField(choices=[('Approuvée', ' approuvée'), ('En attente', 'en attente'), ('Refusée', 'refusée')], default='En attente', max_length=100)),
                ('nom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
