# Generated by Django 5.2.8 on 2025-11-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandedecaissement',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='demandedecaissement',
            name='status',
            field=models.CharField(choices=[('Approuvée', ' approuvée'), ('En attente', 'en attente'), ('Refusée', 'refusée'), ('Decaissé', 'Decaissé')], default='En attente', max_length=100),
        ),
    ]
