# Generated by Django 5.2.8 on 2025-11-21 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire_app', '0002_demandedecaissement_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandedecaissement',
            name='status',
        ),
        migrations.AddField(
            model_name='demandedecaissement',
            name='approuve_or_refuse_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='approuve_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
