# Generated by Django 5.2.8 on 2025-11-21 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire_app', '0003_remove_demandedecaissement_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandedecaissement',
            name='approuve_or_refuse_by',
        ),
        migrations.AddField(
            model_name='demandedecaissement',
            name='approuve_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_approuvees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandedecaissement',
            name='date_approbation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandedecaissement',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('approuvee_directeur', 'Approuvée par Directeur'), ('refusee_directeur', 'Refusée par Directeur'), ('approuvee_comptable', 'Approuvée par Comptable'), ('refusee_comptable', 'Refusée par Comptable'), ('decaisse', 'Décaissé')], default='en_attente', max_length=50),
        ),
    ]
