# Generated by Django 5.2.8 on 2025-11-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire_app', '0004_remove_demandedecaissement_approuve_or_refuse_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandedecaissement',
            name='date_decaissement',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
