# Generated by Django 5.2.8 on 2025-11-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire_app', '0005_demandedecaissement_date_decaissement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandedecaissement',
            old_name='date',
            new_name='date_demande',
        ),
    ]
