# Generated by Django 5.2.8 on 2025-11-23 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_client', models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise'), ('institution', 'Institution publique'), ('promoteur', 'Promoteur immobilier'), ('autre', 'Autre')], max_length=50)),
                ('raison_sociale', models.CharField(blank=True, max_length=200, null=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(max_length=20)),
                ('telephone_secondaire', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100, null=True)),
                ('pays', models.CharField(max_length=100)),
                ('secteur_activite', models.CharField(blank=True, choices=[('residential', 'Résidentiel'), ('commercial', 'Commercial'), ('industriel', 'Industriel'), ('agricole', 'Agricole'), ('public', 'Public')], max_length=50, null=True)),
                ('source_client', models.CharField(blank=True, choices=[('recommendation', 'Recommandation'), ('site_web', 'Site Web'), ('reseaux_sociaux', 'Réseaux Sociaux'), ('publicite', 'Publicité'), ('ancien_client', 'Ancien Client'), ('autre', 'Autre'), ('salon', 'Salon Professionnel'), ('autre', 'Autre')], max_length=50, null=True)),
                ('notes_internes', models.TextField(blank=True, null=True)),
                ('potentiel_client', models.CharField(blank=True, choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('élevé', 'Élevé')], default='moyen', max_length=20, null=True)),
                ('date_premier_contact', models.DateField(blank=True, null=True)),
                ('est_fidel', models.BooleanField(default=False)),
                ('total_contrats', models.IntegerField(default=0)),
                ('chiffre_affaires_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('commercial_attache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Chantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('nom_chantier', models.CharField(max_length=200)),
                ('adresse_chantier', models.TextField()),
                ('ville_chantier', models.CharField(max_length=100)),
                ('quartier_chantier', models.CharField(blank=True, max_length=100, null=True)),
                ('pays_chantier', models.CharField(max_length=100)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('type_travaux', models.CharField(choices=[('charpente_metallique', 'Charpente Métallique'), ('toiture_tole', 'Toiture en Tôle'), ('couverture', 'Couverture'), ('isolation', 'Isolation'), ('ventilation', 'Ventilation'), ('etancheite', 'Étanchéité'), ('garde_corps', 'Garde-Corps'), ('escalier_metal', 'Escalier en Métal'), ('porte_grillee', 'Porte/Grille Métallique'), ('mixte', 'Travaux Mixtes'), ('autre', 'Autre')], max_length=50)),
                ('type_batiment', models.CharField(choices=[('maison_individuelle', 'Maison Individuelle'), ('appartement', 'Appartement'), ('entrepot', 'Entrepôt'), ('usine', 'Usine'), ('bureau', 'Bureau'), ('commerce', 'Commerce'), ('ferme', 'Batiment Agricole'), ('batiment_public', 'Batiment Public'), ('autre', 'Autre')], max_length=50)),
                ('surface_totale', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('hauteur_batiment', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('description_detaille', models.TextField(blank=True, null=True)),
                ('date_debut_prevue', models.DateField(blank=True, null=True)),
                ('date_fin_prevue', models.DateField(blank=True, null=True)),
                ('date_debut_reelle', models.DateField(blank=True, null=True)),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('duree_estimee', models.IntegerField(blank=True, null=True)),
                ('budget_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cout_materiaux_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cout_main_oeuvre_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('marge_beneficiaire_estimee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status_chantier', models.CharField(choices=[('devis', 'Devis en Cours'), ('planification', 'Planification'), ('en_cours', 'En Cours'), ('suspendu', 'Suspendu'), ('termine', 'Terminé'), ('facturee', 'Facturée'), ('paye', 'Payée'), ('annule', 'Annulé')], default='devis', max_length=50)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=20)),
                ('plans_joins', models.BooleanField(default=False)),
                ('photos_avant', models.BooleanField(default=False)),
                ('photos_apres', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('chef_de_chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chantiers_chef', to=settings.AUTH_USER_MODEL)),
                ('equipe_affectee', models.ManyToManyField(blank=True, related_name='chantiers_participants', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chantiers', to='client_app.client')),
            ],
            options={
                'verbose_name': 'Chantier',
                'verbose_name_plural': 'Chantiers',
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenre_contrat', models.CharField(max_length=50, unique=True)),
                ('date_signature', models.DateField(blank=True, null=True)),
                ('mode_paiement', models.CharField(choices=[('comptant', 'Comptant'), ('tranche', 'Tranche'), ('credit', 'Crédit'), ('autre', 'Autre')], default='comptant', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('acompte_pourcentage', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('nombre_tranches', models.IntegerField(default=1)),
                ('montant_encaisse', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('date_du_dernier_paiement', models.DateField(blank=True, null=True)),
                ('contrat_pdf', models.FileField(blank=True, null=True, upload_to='contrats/')),
                ('devis_initial', models.FileField(blank=True, null=True, upload_to='devis/')),
                ('garantie_mois', models.IntegerField(default=12)),
                ('notes_contractuelles', models.TextField(blank=True, null=True)),
                ('chantier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chantiers', to='client_app.chantier')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
            },
        ),
        migrations.CreateModel(
            name='TranchePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tranche', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_prevue', models.DateField()),
                ('date_reelle', models.DateField(blank=True, null=True)),
                ('est_payee', models.BooleanField(default=False)),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranches', to='client_app.contrat')),
            ],
            options={
                'verbose_name': 'Tranche de Paiement',
                'verbose_name_plural': 'Tranches de Paiement',
                'ordering': ['numero_tranche'],
            },
        ),
    ]
