# Generated by Django 5.2.8 on 2025-11-27 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chantier_app', '0001_initial'),
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='chantier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chantiers', to='chantier_app.chantier'),
        ),
        migrations.DeleteModel(
            name='Chantier',
        ),
    ]
